severinstrobl/overlap

.travis.yml

For commits to the dedicated branch 'coverity_scan', a Coverity Scan is
automatically performed using the Travis CI infrastructure.

Adding support for Coverty Scan.

---

test/CMakeLists.txt
test/common.hpp
test/decompose_elements.cpp
test/sphere_element_overlap.cpp
test/sphere_element_overlap_edgecases.cpp
test/sphere_tet_overlap_edgecases.cpp

These are test cases where either the correct result is obvious or edge
cases that were used to identify shortcomings in the overlap
calculation.

Added series of test cases.

---

.travis.yml

The automatically tested compilers are now:
- GCC:
- 5.5.0
- 6.4.0
- 7.4.0
- 8.3.0
- Clang:
- 3.9.1
- 4.0.1
- 5.0.2
- 6.0.1
- 7.1.0
- 8.0.1

Switched to Bionic environment for Travis CI.

---

.github/workflows/python.yaml
.github/workflows/wheels.yaml
.gitmodules
CMakeLists.txt
README.md
pyproject.toml
python/CMakeLists.txt
python/__init__.py
python/overlap.cpp
setup.py
test/CMakeLists.txt
test/detail_regularizedWedge.cpp
test/detail_regularizedWedgeArea.cpp
test/test_overlap.py

This series of commits adds a Python version for the `overlap` library by wrapping the C++ code via `pybind11`. The CI setup was extended to automatically build Python wheels for the most relevant configurations.  
This closes #13.

Python bindings

---

.github/workflows/build.yaml

Older compiler versions were removed from the CI images, so an explicit installation is required for GCC 7/8 and Clang 8/9.

Install additional compiler versions for CI

---

.github/workflows/python.yaml

The Python packages should now be built only when triggered via a special comment 'build python' or in case the action was triggered manually.

Only build Python packages on request

---

.github/workflows/wheels.yaml

The Python wheels/packages should now be built only when triggered via a special comment '/build_wheels' or in case the action was triggered manually.

Only build Python wheels on request

---

.github/workflows/wheels.yaml

Instead of installing a fixed (potentially outdated) version, just pull the latest one from pip, currently this is 2.2.2.

Update cibuildwheel to latest version

---

.cmake-format.py
.github/workflows/python.yaml
.github/workflows/wheels.yaml
CMakeLists.txt
python/CMakeLists.txt
setup.py
test/CMakeLists.txt

Instead of eventually failing in `pybind11`, Python 3 support is now explicitly requested, which also means the minimum required CMakeversion is now 3.12.
Also auto-formatted all CMake files using `cmake-format`.

Explicit dependency on Python 3 and CMake brush-up

---

test/CMakeLists.txt
test/sphere_element_area_edgecases.cpp

Building the project using musl libc fails, as musl does not provide `feenableexcept()`, which seems to be specific to GNU libc on Linux.

Ensure feenableexcept is available

---

.github/workflows/wheels.yaml
python/CMakeLists.txt

The explicit handling of the Python variables seems to not be required any more with recent versions of `scikit-build`.

Fix configure error related to Python components

---

.github/workflows/wheels.yaml

Also concretized build environments for wheels for MacOS/Windows.

Skip trying to build wheels for Python 3.6

---

README.md
include/overlap/overlap.hpp
python/overlap/overlap.cpp
tests/python/test_overlap.py
tests/src/common.hpp
tests/src/test_decompose_elements.cpp
tests/src/test_detail_clamp.cpp
tests/src/test_detail_regularizedWedge.cpp
tests/src/test_detail_regularizedWedgeArea.cpp
tests/src/test_elements.cpp
tests/src/test_normal_newell.cpp
tests/src/test_polygon.cpp
tests/src/test_sphere.cpp
tests/src/test_sphere_element_area_edgecases.cpp
tests/src/test_sphere_element_overlap.cpp
tests/src/test_sphere_element_overlap_edgecases.cpp
tests/src/test_sphere_hex_area.cpp
tests/src/test_sphere_tet_area.cpp
tests/src/test_sphere_tet_overlap_edgecases.cpp

The library now uses a dedicated namespace `overlap` to avoid potential name conflicts when including the library in other projects. Only the types and methods forming the public API are exposed in this namespace, everything else is contained in the namespace `overlap::detail`.
Also, the free functions to calculate the overlap volume and areas are renamed to `overlap_volume` and `overlap_area`, respectively.

Introduce namespace 'overlap'

---

setup.py

Currently, attempting to install the python bindings fails with the following error message:
```
$ pip install overlap
Collecting overlap
Using cached overlap-0.1.0.tar.gz (3.8 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [15 lines of output]
Traceback (most recent call last):
File "/home/kale/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/home/kale/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File …
```

Support packaging>=22.0 (python build dependency)

---

.github/workflows/benchmarks.yml
.github/workflows/run_benchmarks.yml
.gitmodules
CMakeLists.txt
benchmarks/CMakeLists.txt
benchmarks/details.cpp
benchmarks/hex_overlap.cpp

Added some simple benchmarks, two for the overall performance, one for `normal_newell` and `regularized_wedge`, respectively. The benchmarks are also triggered via a dedicated CI job when opening pull requests, hopefully allowing to easily spot deteriorating performance.

Integration of basic C++ benchmarks

---

.github/workflows/benchmarks.yaml
include/overlap/overlap.hpp

With `if constepxr` provided by C++17 there is no need to push the calculation of the polygon area down to the derived classes. In fact, the derived classes can now simply be type aliases for the generic polygon class.

Unify polygon implementation in base class

---

benchmarks/CMakeLists.txt
benchmarks/common.hpp
benchmarks/details.cpp
benchmarks/hex_overlap.cpp
benchmarks/tet_overlap.cpp

Additional changes:
- factored out common benchmarking boilerplate
- increased the minimum number of iterations to improve stats

chore: benchmarks for tet overlap

---

.github/dependabot.yml

In addition to the master branch, _dependabot_ should also keep the GitHub actions in the development branch up to date.

Enable dependabot also for development branch

---

.github/workflows/python.yaml

Added Python 3.11 and 3.12 while removing the end-of-life versions 3.6 and 3.7 in the CI pipeline.

ci: update Python versions

---

pyproject.toml
python/overlap/CMakeLists.txt
python/overlap/__init__.py
python/overlap/overlap.cpp
setup.py

The modern _scikit-build-core_ provides a number of improvements over the older _scikit-build_. Apart from full support for _pyproject.toml_, editable installs work out of the box. The handling of build requirements is greatly improved, as well as the detection of the Python environment using _CMake_.

feat: switch from scikit-build to scikit-build-core

---

.github/workflows/ci.yaml
.github/workflows/coverage.yaml

This should avoid the rate limiting issues stemming from using the shared token instead of the project's own token.

ci: bump Codecov to version 4 and inherit secret

---

include/overlap/overlap.hpp
tests/src/test_normal_newell.cpp
tests/src/test_sphere_tet_overlap_edgecases.cpp

When examining the length of the normal vector obtained using Newell's method prior to the actual normalization, the length scale has to be taken into account.
Fixes: #96

fix: consider length scale in normalization

---

include/overlap/overlap.hpp
tests/src/test_sphere_tet_overlap_edgecases.cpp

In case the line formed by the intersection  of the two planes forming the
general wedge is tangential to (or numerically even beyond) the surface of the
sphere, the volume/area is zero.
---
Fixes: #104

fix: edge case of general spherical wedge beyond sphere

---

.github/workflows/benchmarks.yaml

Instead of creating a new comment, the benchmark action should update the existing comment when run on the same PR multiple times.

ci: update comment using benchmark action

---

.github/workflows/cpp.yaml
.github/workflows/python.yaml
include/overlap/overlap.hpp
tests/src/common.hpp
tests/src/test_double_precision.cpp
tests/src/test_sphere_hex_area.cpp

- test: added detection of constexpr functions
- ci: run C++ build on macOS/AArch64
- test: adapt test expectation on AArch64
- perf: optimize calculation of circular segment area
- test: debugging test on AArch64
- fix: increase allowed epsilon for test failing on AArch64
- ci: build project on AArch64

ci: build project on AArch64
